"rules_envfile"

BUILD_DOT_BAZEL = '''
filegroup(
    name="environment"
    srcs=["environment.bzl"],
    visibility=["//visibility:public"]
)
'''

def _envfile_impl(repository_ctx):
    files = repository_ctx.attr.files
    lines = ["# Generated by rules_envfile - do not modify"]

    for file in files:
        path = repository_ctx.path(file)
        content = repository_ctx.read(path)
        lines.append(content)

    env_file = "\n".join(lines)
    repository_ctx.file("environment.bzl", env_file)
    repository_ctx.file("BUILD.bazel", BUILD_DOT_BAZEL)

envfile = repository_rule(
    implementation = _envfile_impl,
    attrs = {
        "files": attr.label_list(
            allow_files = [".env"],
            doc = "Files containing environment variables",
        ),
    },
)
